#!/bin/sh

#Autostart
#feh --bg-scale ~/Descargas/background.jpg &
# gummy start &
caffeine start &
feh --bg-scale /home/ian/Pictures/wallpaper.jpg
pgrep -x picom > /dev/null || picom &
#spotify &
nm-applet &
sudo ntpd -qg &
#alacritty & 
#udiskie &
firefox --browser &
#sh ~/.config/polybar/./launch.sh &
/usr/lib/kdeconnectd && kdeconnect-indicator &
dunst &
pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V 
bspc config border_width        1
bspc config window_gap          13

bspc config split_ratio          0.52

bspc config borderless_monocle true
bspc config single_monocle true
bspc config gapless_monocle false

bspc config normal_border_color		      "#18262f"
#bspc config active_border_color           "#999999"
bspc config focused_border_color	      "#5e81ac"
#bspc config unfocused_border_color	      "#ffbfd8"
#bspc rule -a Synapse border=off
#bspc config presel_feedback_color	      "#5e81ac"
#bspc config urgent_border_color 	      "#dd2727"
#bspc config -n 3 border_width 0
#bspc config -n $(bspc query -N -n) border_width 0

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^5'
bspc rule -a Emacs state=tiled
bspc rule -a gammy state=floating
bspc rule -a feh state=floating
bspc rule -a Steam desktop='IV' state=floating follow=off
bspc rule -a Alacritty state=floating rectangle=500x200+450+300
bspc rule -a copyq state=floating
bspc rule -a Gpaste-ui state=floating center=true rectangle=500x200+450+300
bspc rule -a mpv state=floating center=on
# bspc rule -a translate state=floating rectangle=339x180+0+0
bspc rule -a translate state=floating rectangle=342x159+528+550
bspc rule -a traductor state=floating rectangle=342x159+528+550
bspc rule -a Harmonoid state=pseudo_tiled rectangle=857x482+528+550
bspc rule -a kitty state=tiled 
bspc rule -a Shift-kitty state=floating rectangle= 685x324+328+201
bspc rule -a Sxiv state=floating
bspc rule -a robloxplayerlauncher.exe state=floating
bspc rule -a Puntos state=floating
bspc rule -a main.py state=floating focus=off follow=off

# Aregalr el cursor 'x'
xsetroot -cursor_name left_ptr &

# Scripts
sh /home/ian/.config/bspwm/BorderFloating.sh &
bspc rule -a Xsnow state=floating border=off
