vim.cmd[[hi VimwikiHeader1 term=bold ctermfg=Red guifg=#a9edeb gui=bold]]
vim.cmd[[hi VimwikiHeader2 term=bold ctermfg=Red guifg=#f7ed9e gui=bold]]
vim.cmd[[hi VimwikiHeader3 term=bold ctermfg=Red guifg=#f1c073 gui=bold]]
vim.cmd[[hi VimwikiHeader4 term=bold ctermfg=Red guifg=#ef68c7 gui=bold]]
vim.cmd[[hi VimwikiHeader5 term=bold ctermfg=Red guifg=#b2a4eb gui=bold]]
vim.cmd[[hi VimwikiHeader6 term=bold ctermfg=Red guifg=#AB65AF gui=bold]]
vim.cmd[[hi VimwikiLink gui=underline cterm=underline guifg=#6FADED]]
vim.cmd[[hi Comment ctermfg=243 guifg=#65737e gui=italic]]
vim.cmd[[hi VimwikiDelText term=bold guifg=#FF3A72 gui=bold,italic]]
-- vim.cmd[[" hi FloatBorder guifg=#3d59a1 guibg=none]]
vim.cmd[[hi Pmenu ctermfg=0 ctermbg=13 guifg=#c0caf5 guibg=NONE]]
--[[
vim.cmd[[" hi LspFloatWinNormal guibg=none]]
vim.cmd[[" hi NormalFloat guibg=none]]
vim.cmd[[" hi CmpDocumentationBorder guibg=none]]
vim.cmd[[" hi CmpDocumentation guibg=none]]
vim.cmd[[" hi TabLine guibg=NONE]]
vim.cmd[[" hi debugPC guibg=NONE]]
vim.cmd[[" hi WhichKeyFloat guibg=NONE]]
vim.cmd[[" hi BufferVisibleIndex guibg=NONE]]
vim.cmd[[" hi SignColumnSB guibg=NONE]]
vim.cmd[[" hi NormalSB guibg=NONE]]
--]]
vim.cmd[[highlight NormalFloat guibg=none]]
-- vim.cmd[["highlight FloatBorder guifg=#f08080 guibg=NONE]]
vim.cmd[[highlight FloatBorder guifg=#292E42 guibg=NONE]]
-- vim.cmd[[" hi Pmenu ctermfg=0 ctermbg=13 guifg=#f08080]]
vim.cmd[[hi DiagnosticVirtualTextError guibg=none gui=italic]]
vim.cmd[[hi DiagnosticVirtualTextWarn guibg=none gui=italic ]]
vim.cmd[[hi DiagnosticVirtualTextInfo guibg=none gui=italic ]]
vim.cmd[[hi DiagnosticVirtualTextHint guibg=none gui=italic]]
vim.cmd[[highlight clear StatusLine]]
vim.cmd[[hi TabbyHL_7aa2f7_NONE_NONE guifg=#C2CAFF]]
